version: '3'
services:
  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/mysql:/var/lib/mysql
      - ./docker/sql:/docker-entrypoint-initdb.d
    #      - /docker/sql:/etc/mysql/conf.d
    networks:
      - auth-network
  keycloak:
    image: jboss/keycloak
    environment:
      KEYCLOAK_USER: keycloak
      KEYCLOAK_PASSWORD: password
      DB_PORT: 3306
      DB_DATABASE: keycloak
      DB_PASSWORD: password
      DB_USER: keycloak
      DB_VENDOR: mariadb
      DB_SCHEMA: keycloak
      KEYCLOAK_LOGLEVEL: debug
    ports:
      - "8081:8080"
    networks:
      - auth-network
    depends_on:
      - mariadb
networks:
  auth-network:
    driver: bridge