version: '3'
services:
  photo-album-service:
    image: 500536527570.dkr.ecr.us-west-1.amazonaws.com/photo-album-service:latest
    env_file:
      - ./docker/photo-album-service.env
    ports:
      - "8080:8080"
    networks:
      - auth-network
    volumes:
      - ./docker/images:/tmp/images
  mariadb:
    image: mariadb:10.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password131
      MYSQL_DATABASE: pas
      MYSQL_USER: user131
      MYSQL_PASSWORD: password131
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/mysql:/var/lib/mysql
      - ./docker/sql:/docker-entrypoint-initdb.d
    networks:
      - auth-network
  keycloak:
    image: jboss/keycloak
    environment:
      KEYCLOAK_USER: keycloak131
      KEYCLOAK_PASSWORD: password131
      DB_PORT: 3306
      DB_DATABASE: keycloak
      DB_PASSWORD: password131
      DB_USER: keycloak131
      DB_VENDOR: mariadb
      DB_SCHEMA: keycloak
#      KEYCLOAK_LOGLEVEL: DEBUG
    volumes:
      - ./docker/keystore/keycloak:/etc/x509/https
    ports:
      - "8081:8080"
      - "8443:8443"
    container_name: keycloak.kooriim.com
    networks:
      - auth-network
networks:
  auth-network:
    driver: bridge