server:
  port: ${SERVER_PORT}
  servlet:
    contextPath: /photo-album-service
spring:
  security:
    #    user:
    #      name: user
    #      password: password
    #      roles: ACTUATOR
    oauth2:
      resourceserver:
        jwt:
          introspection-uri: ${JWT_INTROSPECTION_URI}
          issuer-uri: ${JWT_ISSUER_URI}
          jwk-set-uri: ${JWT_SET_URI}
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        jdbc:
          batch_size: 50
        order_inserts: true
    hibernate:
      ddl-auto: none
    show-sql: true
image-directory: /opt/images
keycloak:
  realm: kooriim
  resource: kooriim
  auth-server-url: ${KEYCLOAK_AUTH-SERVER_URL}
  public-client: true
  principal-attribute: preferred_username
management:
  #  context-path: /manage
  #  endpoints:
  #    web:
  #      exposure:
  #        include: "info"
  security:
    enabled: false