server:
  port: 8080
  servlet:
    contextPath: /photo-album-service
#  ssl:
#    enabled: false
#    key-alias: keycloak
#    key-store: classpath:keystore.p12
#    key-store-password: "password"
#    key-store-type: PKCS12
spring:
  security:
#    user:
#      name: user
#      password: password
#      roles: ACTUATOR
    oauth2:
      resourceserver:
        jwt:
          introspection-uri: https://keycloak.kooriim.com:8443/auth/realms/kooriim-fe/protocol/openid-connect/token/introspect
          issuer-uri: https://keycloak.kooriim.com:8443/auth/realms/kooriim-fe
          jwk-set-uri: https://keycloak.kooriim.com:8443/auth/realms/kooriim-fe/protocol/openid-connect/certs
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  datasource:
    url: jdbc:mysql://localhost:3306/pas?zeroDateTimeBehavior=convertToNull
    username: user131
    password: password131
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        jdbc:
          batch_size: 50
        order_inserts: true
    hibernate:
      ddl-auto: none
    show-sql: true
image-directory: /tmp/images
keycloak:
  realm: kooriim-fe
  resource: kooriim-fe
  auth-server-url: https://keycloak.kooriim.com:8443/auth
  public-client: true
  principal-attribute: preferred_username
management:
  security:
    enabled: false
require-ssl: false
allowed-origin: "*"
s3:
  bucketName: kooriim-images-test